build:
  stage: build
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN git.case.edu:4567
    - docker build -t git.case.edu:4567/hacsoc/acm.case.edu:latest .
    - docker push git.case.edu:4567/hacsoc/acm.case.edu:latest
